Repository TandaHQ/definitions, pull requests merged in 2022-09, with the labels that each got.

#43 PFC-4672 (fix) Mourning for Queen Elizabeth II (au only)
  au.yaml
Labels: bug

#44 PFC-4676 (fix) Mourning for Queen Elizabeth II (nz only)
  au.yaml
  nz.yaml
  nz2_calendar_dates.yaml
Labels: bug

#46 ISD-12423 - Add new Bank hol for UK
  gb.yaml
Labels: question

#47 ISD-12423 - Remove new BH for UK
  gb.yaml
Labels: enhancement
